services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
    command: npm run start:dev product
    env_file:
      - ./apps/product/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app