# product-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: gabz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: armand96/gabz:product-v1
          ports:
            - containerPort: 3001
          env:
            - name: DB_WRITE_HOST
              value: mysql
            - name: DB_WRITE_PORT
              value: "3306"
            - name: DB_WRITE_USERNAME
              value: "root"
            - name: DB_WRITE_PASSWORD
              value: "password"
            - name: DB_WRITE_NAME
              value: "product_read_db"
            - name: DB_READ_HOST
              value: mysql
            - name: DB_READ_PORT
              value: "3306"
            - name: DB_READ_USERNAME
              value: "root"
            - name: DB_READ_PASSWORD
              value: "password"
            - name: DB_READ_NAME
              value: "product_read_db"
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: gabz
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
